# Netlify configuration for National Park Service hiring analysis

# Ignore builds unless files in this directory change
[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- analysis/national_park_service/"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"